services:
  grafana:
      image: grafana/grafana:latest
      ports:
       - '3010:3000'
      restart: always
      environment:
       GF_SECURITY_ADMIN_PASSWORD: aSim#2024qaz
       GF_USERS_ALLOW_SIGN_UP: false
       GF_SERVER_DOMAIN: 172.30.255.80
       GF_RENDERING_SERVER_URL: http://renderer:8081/render
       GF_RENDERING_CALLBACK_URL: http://grafana:3000/
       GF_LOG_FILTERS: rendering:debug
      volumes:
       - ./grafana-data:/var/lib/grafana
      user: "0"
  renderer:
      container_name: grafana-image-renderer
      image: grafana/grafana-image-renderer:latest
      ports:
       - 8081
      restart: always
      links:
       - grafana
