services:
  grafana:
      image: grafana/grafana:8.1.8
      ports:
       - '9000:3000'
      restart: always
      environment:
       #GF_RENDERING_SERVER_URL: http://renderer:8081/render
       #GF_RENDERING_SERVER_URL: http://renderer:8082/render
       #GF_RENDERING_CALLBACK_URL: http://grafana:3000/
       #GF_RENDERING_CALLBACK_URL: http://grafana:9000/
       GF_LOG_FILTERS: rendering:debug
       GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
       GF_SECURITY_ADMIN_USER: admin
       GF_SECURITY_ADMIN_PASSWORD: Asim#2024qaz
      volumes:
       - ./grafana-data:/var/lib/grafana
       - ./grafana:/etc/grafana
       user: $PUID
  renderer:
      image: grafana/grafana-image-renderer:3.5.0
      ports:
        #- 8081:8081
        - 8082:8081
      restart: always
#volumes:
 #grafana-data1:
 #grafana1:
