services:
  grafana:
      image: grafana/grafana:8.1.8
      ports:
       - '3000:3000'
      restart: always
      environment:
       GF_RENDERING_SERVER_URL: http://renderer:8081/render
       GF_RENDERING_CALLBACK_URL: http://grafana:3000/
       GF_LOG_FILTERS: rendering:debug
      volumes:
       - ./grafana-data:/var/lib/grafana
       - ./grafana:/etc/grafana
  renderer:
      image: grafana/grafana-image-renderer:3.5.0
      ports:
        - 8081:8081
      restart: always
volumes:
 grafana-data1:
 grafana1:
